"""add main_domain to projects

Revision ID: be3f32300bd3
Revises: af72786bbb09
Create Date: 2026-02-07 23:55:01.523819

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3f32300bd3'
down_revision: Union[str, None] = 'af72786bbb09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('main_domain', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'main_domain')
    # ### end Alembic commands ###
